[flask]
DEBUG = false
# Replace with secure value
SECRET_KEY = "REPLACE_ME"
SESSION_COOKIE_NAME = "mm_session"
# Change to `true` if hosting
SESSION_COOKIE_SECURE = false

[app]
# Change this before first run if you want
name = "MediaMirror"

[users]
# Credentials of default admin account
default_username = "Admin"
default_password = "123456"

[database]
# Don't change unless you're doing something weird
schema_directory = "./schema_revisions"
# Update with your DB connection details
dialect = "postgresql"
driver = "psycopg2"
username = "USER"
password = "PASSWORD"
db_host = "localhost"
db_port = 5432
database_name = "DATABASE_NAME"

[logging]
logging_directory = "./logs"
# ZSTD compression for rotated log files
use_compression = false
# Number of log backups to keep (0 = keep all logs)
backup_count = 0

# https://docs.python.org/3/library/logging.config.html#configuration-dictionary-schema
[log_config]
version = 1
disable_existing_loggers = true

# App Components
[log_config.loggers.app]
level = "INFO"
handlers = ["console", "file"]
[log_config.loggers.api]
level = "WARN"
handlers = ["console", "file"]
[log_config.loggers."services.database_manager"]
level = "WARN"
handlers = ["console", "file"]
[log_config.loggers."services.auth"]
level = "WARN"
handlers = ["console", "file"]

# Libraries
[log_config.loggers.flask]
level = "CRITICAL"
handlers = ["console"]
[log_config.loggers.werkzeug]
level = "CRITICAL"
handlers = ["file"]
[log_config.loggers.sqlalchemy]
level = "WARN"
handlers = ["file"]
[log_config.loggers.alembic]
level = "WARN"
handlers = ["file"]
[log_config.loggers.jinja2]
level = "WARN"
handlers = ["file"]
[log_config.loggers.apispec]
level = "WARN"
handlers = ["file"]
[log_config.loggers.marshmallow]
level = "WARN"
handlers = ["file"]
[log_config.loggers."py.warnings"]
level = "WARN"
handlers = ["console", "file"]
